{% set name = "sphinx-click" %}
{% set version = "6.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: f5d664321dc0c6622ff019f1e1c84e58ce0cecfddeb510e004cf60c2a3ab465b

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - pbr >=2.0
  run:
    - python >={{ python_min }}
    - sphinx >=2.0
    - click >=6.0

test:
  imports:
    - sphinx_click
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/sphinx-click/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Sphinx plugin to automatically document click-based applications
  description: |
    sphinx-click is a Sphinx plugin that allows you to automatically extract 
    documentation from a click-based application and include it in your docs.
  doc_url: https://sphinx-click.readthedocs.io/en/latest/
  dev_url: https://github.com/click-contrib/sphinx-click

extra:
  recipe-maintainers:
    - CurtLH
    - williamjamir
