# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "6.1.0"
  python_check_max: "3.14"

package:
  name: sphinx-click
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/s/sphinx-click/sphinx_click-${{ version }}.tar.gz
  sha256: c702e0751c1a0b6ad649e4f7faebd0dc09a3cc7ca3b50f959698383772f50eef

build:
  number: 1
  noarch: python
  script:
    env:
      SETUPTOOLS_SCM_PRETEND_VERSION: ${{ version }}
    content:
      - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools >=80
    - setuptools-scm >=8
  run:
    - click >=8.0
    - docutils
    - python >=${{ python_min }}
    - sphinx >=4.0

tests:
  - python:
      imports: sphinx_click
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - ${{ python_check_max }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      # catch build system drift for bad `0.0.0` versions
      - python -c "v = __import__('importlib.metadata').metadata.version('sphinx-click'); print(v); assert v == '${{ version }}'"

about:
  license: MIT
  license_file: LICENSE
  summary: A Sphinx plugin to automatically document click-based applications
  description: |
    sphinx-click is a Sphinx plugin that allows you to automatically extract
    documentation from a click-based application and include it in your docs.
  homepage: https://pypi.org/project/sphinx-click/
  repository: https://github.com/click-contrib/sphinx-click
  documentation: https://sphinx-click.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - CurtLH
    - williamjamir
